<?php

namespace ContainerP6XjXs2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N26u0jcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.N26u0jc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N26u0jc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'competence' => ['privates', '.errored..service_locator.N26u0jc.App\\Entity\\Competence', NULL, 'Cannot autowire service ".service_locator.N26u0jc": it references class "App\\Entity\\Competence" but no such service exists.'],
            'competenceRepository' => ['privates', 'App\\Repository\\CompetenceRepository', 'getCompetenceRepositoryService', true],
        ], [
            'competence' => 'App\\Entity\\Competence',
            'competenceRepository' => 'App\\Repository\\CompetenceRepository',
        ]);
    }
}
