<?php

namespace ContainerKM2vbAc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QGXyHk2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QGXyHk2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QGXyHk2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CompetenceController::delete' => ['privates', '.service_locator.N26u0jc', 'get_ServiceLocator_N26u0jcService', true],
            'App\\Controller\\CompetenceController::edit' => ['privates', '.service_locator.N26u0jc', 'get_ServiceLocator_N26u0jcService', true],
            'App\\Controller\\CompetenceController::index' => ['privates', '.service_locator.Z9fkP2I', 'get_ServiceLocator_Z9fkP2IService', true],
            'App\\Controller\\CompetenceController::new' => ['privates', '.service_locator.Z9fkP2I', 'get_ServiceLocator_Z9fkP2IService', true],
            'App\\Controller\\CompetenceController::show' => ['privates', '.service_locator.oodVOBr', 'get_ServiceLocator_OodVOBrService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\CompetenceController:delete' => ['privates', '.service_locator.N26u0jc', 'get_ServiceLocator_N26u0jcService', true],
            'App\\Controller\\CompetenceController:edit' => ['privates', '.service_locator.N26u0jc', 'get_ServiceLocator_N26u0jcService', true],
            'App\\Controller\\CompetenceController:index' => ['privates', '.service_locator.Z9fkP2I', 'get_ServiceLocator_Z9fkP2IService', true],
            'App\\Controller\\CompetenceController:new' => ['privates', '.service_locator.Z9fkP2I', 'get_ServiceLocator_Z9fkP2IService', true],
            'App\\Controller\\CompetenceController:show' => ['privates', '.service_locator.oodVOBr', 'get_ServiceLocator_OodVOBrService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\CompetenceController::delete' => '?',
            'App\\Controller\\CompetenceController::edit' => '?',
            'App\\Controller\\CompetenceController::index' => '?',
            'App\\Controller\\CompetenceController::new' => '?',
            'App\\Controller\\CompetenceController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CompetenceController:delete' => '?',
            'App\\Controller\\CompetenceController:edit' => '?',
            'App\\Controller\\CompetenceController:index' => '?',
            'App\\Controller\\CompetenceController:new' => '?',
            'App\\Controller\\CompetenceController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
