<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKM2vbAc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKM2vbAc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKM2vbAc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKM2vbAc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKM2vbAc\App_KernelDevDebugContainer([
    'container.build_hash' => 'KM2vbAc',
    'container.build_id' => '46cc92e1',
    'container.build_time' => 1669367880,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKM2vbAc');
